/* 🤖 this file was generated by svg-to-ts */
export * from './build/nephos-figma.icon.mjs';
export * from './build/nephos-github.icon.mjs';
export * from './build/nephos-linkedin.icon.mjs';
export * from './build/my-icons.model.mjs';
